
const actions = {
  SET_FORMS: 'SET_FORMS',
  SET_FORM: 'SET_FORM',
  CREATE_FORM: 'CREATE_FORM',
  SET_FIELDS: 'SET_FIELDS',
  SET_TITLE: 'SET_TITLE',
  SET_FILLING_FORM: 'SET_FILLING_FORM',
  UPDATE_ANSWER: 'UPDATE_ANSWER'
}

export { actions }